controller:
  replicaCount: 2
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: autoscaling.lab/app
            operator: DoesNotExist
  progressDeadlineSeconds: 30
  ingressClassResource:
    name: nginx
    enabled: true
  extraArgs:
    default-ssl-certificate: "ingress-nginx/wildcard-k8s-lab-tls"
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "10254"
  resources:
    requests:
      cpu: 800m
      memory: 200Mi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack
