nodeSelector:
  autoscaling.lab/monitoring: "yes"

prometheus:
  url: http://kube-prometheus-stack-prometheus.monitoring

rules:
  default: false
  external:
    - seriesQuery: 'request_duration_seconds_sum{namespace!="",pod!=""}'
      resources:
        overrides:
          namespace:
            resource: "namespace"
          pod:
            resource: "pod"
      name:
        as: "znn_latency_ms_avg"
      metricsQuery: >
        1000 *
        sum(rate(request_duration_seconds_sum{host="znn"}[30s]))
        /
        sum(rate(request_duration_seconds_count{host="znn"}[30s]))
    - seriesQuery: 'request_duration_seconds_bucket{namespace!="",pod!=""}'
      resources:
        overrides:
          namespace:
            resource: "namespace"
          pod:
            resource: "pod"
      name:
        as: "znn_latency_ms_p95"
      metricsQuery: >
        1000 *
        histogram_quantile(
          0.95,
          sum by (le, namespace) (
            rate(request_duration_seconds_bucket{host="znn"}[30s])
          )
        )
    - seriesQuery: 'request_duration_seconds_bucket{namespace!="",pod!=""}'
      resources:
        overrides:
          namespace:
            resource: "namespace"
          pod:
            resource: "pod"
      name:
        as: "znn_requests_over_1s_ratio"
      metricsQuery: >
        1 -
        (
          sum(rate(request_duration_seconds_bucket{host="znn",le="1.0"}[30s]))
          /
          sum(rate(request_duration_seconds_count{host="znn"}[30s]))
        )
