apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: boutique
  labels:
    app: frontend
spec:
  ingressClassName: "nginx"
  rules:
  - host: boutique.k8s.lab
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: frontend
            port: 
              number: 80
