repositories:
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: grafana
  url: https://grafana.github.io/helm-charts
- name: metallb
  url: https://metallb.github.io/metallb

releases:
- name: metallb
  chart: metallb/metallb
  namespace: metallb-system
  version: 0.14.9
  values:
    - installCRDs: true
    - speaker:
        tolerataMaster: true

- name: ingress-nginx
  namespace: ingress-nginx
  chart: ingress-nginx/ingress-nginx
  version: 4.12.2
  values:
    - controller:
        progressDeadlineSeconds: 30
        ingressClassResource:
          name: nginx
          enabled: true
        podAnnotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "10254"
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
            additionalLabels:
              release: kube-prometheus-stack
            interval: 30s

- name: kube-prometheus-stack
  namespace: monitoring
  chart: prometheus-community/kube-prometheus-stack
  version: 72.6.2
  values:
    - prometheus:
        ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - prometheus.k8s.lab
        prometheusSpec:
          enableRemoteWriteReceiver: true
          maximumStartupDurationSeconds: 120
        service:
          type: LoadBalancer
          loadBalancerIP: 10.0.0.17
          annotations:
            metallb.universe.tf/address-pool: default-pool
    - grafana:
        adminPassword: "admin"
        ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - grafana.k8s.lab

- name: online-boutique
  namespace: boutique
  chart: charts/onlineboutique
  version: 0.10.2
  values: []

