repositories:
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: grafana
  url: https://grafana.github.io/helm-charts
# - name: online-boutique       # helm chart não-oficial porém mantido
#   url: oci://us-docker.pkg.dev/online-boutique-ci/charts/onlineboutique

releases:
- name: ingress-nginx
  namespace: ingress-nginx
  chart: ingress-nginx/ingress-nginx
  version: 4.12.2
  values:
    - controller:
        ingressClassResource:
          name: nginx
          enabled: true
        nodeSelector:
          ingress-ready: "true"
        service:
          type: NodePort
          nodePorts:
            http: 30080
            https: 30443

- name: kube-prometheus-stack
  namespace: observability
  chart: prometheus-community/kube-prometheus-stack
  version: 59.1.0

- name: grafana-dashboards
  namespace: observability
  chart: grafana/grafana
  values:
  - adminPassword: "admin"

- name: online-boutique
  namespace: boutique
  chart: oci://us-docker.pkg.dev/online-boutique-ci/charts/onlineboutique
  version: 0.10.2
  values: []

