repositories:
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: grafana
  url: https://grafana.github.io/helm-charts
- name: metallb
  url: https://metallb.github.io/metallb

releases:
- name: metallb
  chart: metallb/metallb
  namespace: metallb-system
  version: 0.14.9
  values:
    - installCRDs: true
    - speaker:
        tolerataMaster: true

- name: ingress-nginx
  namespace: ingress-nginx
  chart: ingress-nginx/ingress-nginx
  version: 4.12.2
  values:
    - controller:
        progressDeadlineSeconds: 30
        ingressClassResource:
          name: nginx
          enabled: true

- name: kube-prometheus-stack
  namespace: observability
  chart: prometheus-community/kube-prometheus-stack
  version: 72.5.2

- name: grafana-dashboards
  namespace: observability
  chart: grafana/grafana
  version: 9.0.0
  values:
    - adminPassword: "admin"
    - ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - grafana.127.0.0.1.nip.io
        path: /
        pathType: Prefix
    - sidecar:
        datasources:
          enabled: true
          label: grafana_datasource
          searchNamespace: observability
        dashboards:
          enabled: true
          label: grafana_dashboard
          searchNamespace: observability

- name: online-boutique
  namespace: boutique
  chart: oci://us-docker.pkg.dev/online-boutique-ci/charts/onlineboutique
  version: 0.10.2
  values: []

