repositories:
  - name: jetstack
    url: https://charts.jetstack.io
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: twuni
    url: https://helm.twun.io

releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.15.0
    values:
      - crds:
          enabled: true
          keep: false

  - name: metallb
    chart: metallb/metallb
    namespace: metallb-system
    version: 0.14.9
    values:
      - installCRDs: true
      - speaker:
          tolerataMaster: true

  - name: local-path
    namespace: local-path-storage
    chart: charts/local-path-provisioner
    version: 0.0.31
    values:
      - storageClass:
          defaultClass: true

  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.12.2
    needs:
      - metallb-system/metallb
      - cert-manager/cert-manager
    values:
      - values/ingress.yaml

  - name: kube-prometheus-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 73.2.0
    needs: ["ingress-nginx/ingress-nginx"]
    values:
      - values/prometheus.yaml

  - name: prometheus-adapter
    namespace: monitoring
    chart: prometheus-community/prometheus-adapter
    version: 4.14.1
    needs: ["kube-prometheus-stack"]
    values:
      - values/prometheus-adapter.yaml

  - name: cpa-operator
    namespace: cpa-operator
    chart: charts/custom-pod-autoscaler-operator
    version: v1.4.2
    values: []

  - name: online-boutique
    namespace: boutique
    chart: charts/onlineboutique
    version: 0.10.2
    values: []

  - name: registry
    namespace: registry
    chart: twuni/docker-registry
    version: 2.3.0
    values:
      - values/registry.yaml
