apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: znn
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kube-znn
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: External
      external:
        metric:
          name: znn_latency_ms_average
        target:
          type: Value
          value: 1000
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10
      policies:
        - periodSeconds: 15
          value: 100
          type: Percent
