apiVersion: v2
name: custom-self-adapter-operator
description: A Helm chart to distribute custom-self-adapter-operator
type: application

version: 0.1.0
appVersion: "0.1.0"

keywords:
  - kubernetes
  - operator

annotations:
  kubebuilder.io/generated-by: kubebuilder
