apiVersion: custompodautoscaler.com/v1
kind: CustomPodAutoscaler
metadata:
  namespace: default
  name: cpa-python
spec:
  template:
    spec:
      containers:
        - name: cpa-python-znn
          image: registry.k8s.lab/cpa-python:0.1-${TIMESTAMP}
          imagePullPolicy: Always
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kube-znn
  # roleRequiresMetricsServer: true
  # We will provision our own Role in role-cpa-python.yaml
  provisionRole: false