apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cpa-python
  namespace: default
  labels:
    k8s.lab/part-of: cpa-python
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - replicationcontrollers
  - replicationcontrollers/scale
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/scale
  - deployments/status
  - replicasets
  - replicasets/scale
  - replicasets/status
  - statefulsets
  - statefulsets/scale
  - statefulsets/status
  verbs:
  - '*'
- apiGroups:
  - metrics.k8s.io
  - custom.metrics.k8s.io
  - external.metrics.k8s.io
  resources:
  - '*'
  verbs:
  - '*'