apiVersion: custom-self-adapter.net/v1
kind: CustomSelfAdapter
metadata:
  namespace: default
  name: csa-quality
spec:
  template:
    spec:
      nodeSelector:
        adaptation: "yes"
      containers:
        - name: csa-quality-znn
          image: ${IMAGE}:${TAG}
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "128m"
              memory: "128Mi"
            limits:
              cpu: "1024m"
              memory: "1024Mi"
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kube-znn
  roleRequiresMetricsServer: true
