apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: boutique

resources:
  - frontend.yaml
  - currencyservice.yaml
  - cartservice.yaml
  - paymentservice.yaml
  - recommendationservice.yaml

generatorOptions:
  disableNameSuffixHash: true
